### ISSUE TITLE
Clone on multiframe image creates invalid Dicom: Encapsulated pixel data fragment is not even length

### ISSUE THREAD

**Issue by osklu002** [Efferent-Health/fo-dicom.Codecs#36]
I am trying to convert a multi-frame image into Jpeg2000 LS. When I run the following code:

````
public void CreateDicomFile(DicomDataset dicomDataset) 
{
    var inPath = @"C:\temp\multiframe_image.dcm";
    var outPath = @"C:\temp\output.dcm";
    var newDicomFile = DicomFile.Open(inPath);
    var result = newDicomFile.Clone(DicomTransferSyntax.JPEG2000Lossless,
        new FellowOakDicom.Imaging.NativeCodec.DicomJpeg2000Params { UpdatePhotometricInterpretation = false, ProgressionOrder = FellowOakDicom.Imaging.NativeCodec.OPJ_PROG_ORDER.RLCP });
    result.Save(outPath);
}
````
The Dicom that is produced gets the following issue when I am running DicomVerify (https://dclunie.com/dicom3tools/dciodvfy.html):
Warning - Encapsulated pixel data fragment is not even length
[multiframe_image.zip](https://github.com/Efferent-Health/fo-dicom.Codecs/files/10957112/multiframe_image.zip)

**Comment by cbeltran1306** [comment]
Hi @osklu002, we have used this code below, it doesn't have any problem with the transcoder to JPEG2000Lossless.

            new DicomSetupBuilder()
                     .RegisterServices(s => s.AddFellowOakDicom().AddTranscoderManager<NativeTranscoderManager>())
                     .SkipValidation()
                      .Build();

            var file = "multiframe.dcm";
            var data = DicomFile.Open(file).Dataset;

            var output = new DicomFile(data).Clone(DicomTransferSyntax.JPEG2000Lossless, new FellowOakDicom.Imaging.NativeCodec.DicomJpeg2000Params{
                UpdatePhotometricInterpretation = false,
                ProgressionOrder = FellowOakDicom.Imaging.NativeCodec.OPJ_PROG_ORDER.RLCP
            });

            output.Save("output.dcm");

**Comment by jaime-olivares** [comment]
@osklu002 please confirm you are using a code similar to @cbeltran1306 and let us know

**Comment by osklu002** [comment]
Hello, I tried your code. I believe the only difference was that you took the Dataset and recreated the Dicomfile?
Unfortunately I got the same issue, did you also verify your Dicom after? Like I wrote in the original post I do get a dicomfile out but it does not adhere to the standard.

**Comment by osklu002** [comment]
Also not that this depends on the input data. If the data happens to result in a dicomfile with even length pixel data there is no issue

**Comment by osklu002** [comment]
Hello @cbeltran1306 I am not able to share my entire project since it is for work but the code I provided is enough to cause the issue, or am I missing something?

**Comment by osklu002** [comment]
Here is an example project that gets the issue:
https://github.com/osklu002/DicomTest

**Comment by cbeltran1306** [comment]
Hi @osklu002, this issue is not a bug from ourside, in your code you have to modify the UpdatePhotometricInterpretation value as **true** from DicomJpeg2000Params or omit it, because it causes the tag PhotometricInterpretation does not update correctly to **YBR_RCT** instead of **RGB**. Please confirm it and let us know.

      new FellowOakDicom.Imaging.NativeCodec.DicomJpeg2000Params { UpdatePhotometricInterpretation = true, ProgressionOrder = 
        FellowOakDicom.Imaging.NativeCodec.OPJ_PROG_ORDER.RLCP });
        result.Save(outPath);

**Comment by osklu002** [comment]
Hello again, thank you for looking into this. I think I had a bad example since the issue I am trying to ask about is the "Encapsulated pixel data fragment is not even length" which is not resolved by changing "UpdatePhotometricInterpretation = true", that does however remove the other error in dicomverify.

**Comment by cbeltran1306** [comment]
That error you got with **multifram_image.dcm** dicom file?

**Comment by osklu002** [comment]
Yes exactly

**Comment by cbeltran1306** [comment]
When we run your test project, we didn't get any issue, but only if it is missing to set the transcoderManager, as you can below

    new DicomSetupBuilder().RegisterServices(s => 
       s.AddFellowOakDicom().AddTranscoderManager<FellowOakDicom.Imaging.NativeCodec.NativeTranscoderManager> 
       ()).SkipValidation().Build();

will get this error
     
     Unhandled exception. FellowOakDicom.Imaging.Codec.DicomCodecException: Encoding dataset to transfer syntax JPEG 
    2000 Image Compression (Lossless Only) is not supported.
    at FellowOakDicom.Imaging.Codec.DicomTranscoder.Encode(DicomDataset oldDataset, DicomTransferSyntax outSyntax, 
    IDicomCodec codec, DicomCodecParams parameters)
    at FellowOakDicom.Imaging.Codec.DicomTranscoder.Transcode(DicomDataset dataset)
     at FellowOakDicom.Imaging.Codec.DicomTranscoder.Transcode(DicomFile file)
     at FellowOakDicom.Imaging.Codec.DicomCodecExtensions.Clone(DicomFile file, DicomTransferSyntax syntax, 
    DicomCodecParams parameters)

**Comment by osklu002** [comment]
So, trying to clarify a bit better. The Dicom I get, I am then verifying like this:
![dicomverify](https://github.com/Efferent-Health/fo-dicom.Codecs/assets/5138624/a92dd381-6edd-4798-8ba3-51555aba0b4c)

Are you also running the verify after?

**Comment by cbeltran1306** [comment]
Hi @osklu002, we have reproduced it. This is a warning from **dciodvfy** tool, because the dicom file (Jpeg2000) you got has a first frame size different from the other ones, you can see below, it means the uncompressed (**multiframe_image.dcm**) dicom file has not the first frame even length. Please check your original dicom file when you created.

![image](https://github.com/Efferent-Health/fo-dicom.Codecs/assets/38439412/d40609e1-2083-4dad-936a-836ef5595ec7)

**Comment by osklu002** [comment]
But running dciodvfy on the original dicom does not give any warnings/errors?

**Comment by pdgmdm** [comment]
Hello I have the same issue when cloning to transfer syntax JPEGProcess14SV1.
Using DCMTK dcmdump, I get this output.

```
W: DcmItem: Length of element (7fe0,0010) is not a multiple of 2 (VR=OW)
W: DcmSequenceOfItems: Length of item in sequence PixelData (7fe0,0010) is odd
W: DcmSequenceOfItems: Length of item in sequence PixelData (7fe0,0010) is odd
...
```

Note: I am using versions fo-dicom.Codecs 5.10.6 together with fo-dicom 5.1.0

Is there any workaround to fix these odd pixel lengths ?

**Comment by jaime-olivares** [comment]
We will provide a solution within a week from now

**Comment by cbeltran1306** [comment]
Hi guys, this bug has been fixed, please you can use new nuget published https://www.nuget.org/packages/fo-dicom.Codecs/5.10.8

**Comment by pdgmdm** [comment]
Hi @jaime-olivares ,

It seems not completely fixed: now I do not see the odd lengths for the DcmSequenceOfItems, however for the DcmItem it is still present:


`
W: DcmItem: Length of element (7fe0,0010) is not a multiple of 2 (VR=OW)
`

**Comment by cbeltran1306** [comment]
Hi @pdgmdm, can you send your sample dicom file, please?

**Comment by pdgmdm** [comment]
> Hi @pdgmdm, can you send your sample dicom file, please?

Hello @cbeltran1306 , here you can find the sample docomo file and the source code I used to compress.
Note that I used DCMTK's dcmdump and the output starts with 
`W: DcmItem: Length of element (7fe0,0010) is not a multiple of 2 (VR=OW)`

[DicomCompressionTest.zip](https://github.com/Efferent-Health/fo-dicom.Codecs/files/12003177/DicomCompressionTest.zip)
